name: Deploy FuelFlow

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/fuelflow-api
      IMAGE_TAG: latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: '7642'

          script: |
            echo "Acessando diretório de deploy..."
            cd /opt/fuelflow
            
            # 1. Puxa a nova imagem do Docker Hub
            echo "Puxando nova imagem do Docker Hub: ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}"
            docker pull ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}
            
            # 2. Derruba os contêineres antigos
            echo "Parando e removendo contêineres antigos..."
            docker compose down 
            
            # 3. Sobe os novos contêineres usando a imagem puxada
            # Remove o --build
            echo "Iniciando novos contêineres..."
            docker compose up -d
            
            echo "Limpando imagens não utilizadas..."
            docker image prune -f